#!/bin/sh

DTBFILE=/boot/bcm2708-rpi-0-w.dtb
if [ -f "$DTBFILE" ];then
	dtc -W no-unit_address_vs_reg -I dtb -O dts -o /boot/tmp.dts $DTBFILE

	if grep -q "brcm,pins = <0x8 0x7>;" /boot/tmp.dts; then
		if grep -q "brcm,function = <0x1>;" /boot/tmp.dts; then
      			echo "\nZERO-W";
			sed /boot/tmp.dts -i -e "s/brcm,function = <0x6>;/brcm,function = <0x1>;/"
			cp /boot/bcm2708-rpi-0-w.dtb /boot/bcm2708-rpi-0-w.bak	
			dtc -W no-unit_address_vs_reg -I dts -O dtb -o $DTBFILE /boot/tmp.dts 
		fi
	fi
	rm /boot/tmp.dts
fi


DTBFILE=/boot/bcm2708-rpi-0.dtb
if [ -f "$DTBFILE" ];then
	dtc -W no-unit_address_vs_reg -I dtb -O dts -o /boot/tmp.dts $DTBFILE

	if grep -q "brcm,pins = <0x8 0x7>;" /boot/tmp.dts; then
		if grep -q "brcm,function = <0x1>;" /boot/tmp.dts; then
	      		echo "\nZERO";
			sed /boot/tmp.dts -i -e "s/brcm,function = <0x6>;/brcm,function = <0x1>;/"
			cp /boot/bcm2708-rpi-0.dtb /boot/bcm2708-rpi-0.bak	
			dtc -W no-unit_address_vs_reg -I dts -O dtb -o $DTBFILE /boot/tmp.dts 
		fi
	fi
	rm /boot/tmp.dts
fi

DTBFILE=/boot/bcm2708-rpi-b-plus.dtb
if [ -f "$DTBFILE" ];then
	dtc -W no-unit_address_vs_reg -I dtb -O dts -o /boot/tmp.dts $DTBFILE
	if grep -q "brcm,pins = <0x8 0x7>;" /boot/tmp.dts; then
		if grep -q "brcm,function = <0x1>;" /boot/tmp.dts; then
	      		echo "\n1B+";
			sed /boot/tmp.dts -i -e "s/brcm,function = <0x6>;/brcm,function = <0x1>;/"
			cp /boot/bcm2708-rpi-b-plus.dtb /boot/bcm2708-rpi-b-plus.bak
			dtc -W no-unit_address_vs_reg -I dts -O dtb -o $DTBFILE /boot/tmp.dts 
		fi
	fi
	rm /boot/tmp.dts
fi

DTBFILE=/boot/bcm2708-rpi-cm.dtb
if [ -f "$DTBFILE" ];then
	dtc -W no-unit_address_vs_reg -I dtb -O dts -o /boot/tmp.dts $DTBFILE
	if grep -q "brcm,pins = <0x8 0x7>;" /boot/tmp.dts; then
		if grep -q "brcm,function = <0x1>;" /boot/tmp.dts; then
      			echo "\nCM";
			sed /boot/tmp.dts -i -e "s/brcm,function = <0x6>;/brcm,function = <0x1>;/"
			cp /boot/bcm2708-rpi-cm.dtb /boot/bcm2708-rpi-cm.bak
			dtc -W no-unit_address_vs_reg -I dts -O dtb -o $DTBFILE /boot/tmp.dts 
		fi
	fi
	rm /boot/tmp.dts
fi

DTBFILE=/boot/bcm2709-rpi-2-b.dtb
if [ -f "$DTBFILE" ];then
	dtc -W no-unit_address_vs_reg -I dtb -O dts -o /boot/tmp.dts $DTBFILE
	if grep -q "brcm,pins = <0x8 0x7>;" /boot/tmp.dts; then
		if grep -q "brcm,function = <0x1>;" /boot/tmp.dts; then
      			echo "\n2B";
			sed /boot/tmp.dts -i -e "s/brcm,function = <0x6>;/brcm,function = <0x1>;/"
			cp /boot/bcm2709-rpi-2-b.dtb /boot/bcm2709-rpi-2-b.bak
			dtc -W no-unit_address_vs_reg -I dts -O dtb -o $DTBFILE /boot/tmp.dts 
		fi
	fi
	rm /boot/tmp.dts
fi

DTBFILE=/boot/bcm2710-rpi-3-b.dtb
if [ -f "$DTBFILE" ];then
	dtc -W no-unit_address_vs_reg -I dtb -O dts -o /boot/tmp.dts $DTBFILE
	if grep -q "brcm,pins = <0x8 0x7>;" /boot/tmp.dts; then
		if grep -q "brcm,function = <0x1>;" /boot/tmp.dts; then
      			echo "\n3B";
			sed /boot/tmp.dts -i -e "s/brcm,function = <0x6>;/brcm,function = <0x1>;/"
			cp /boot/bcm2710-rpi-3-b.dtb /boot/bcm2710-rpi-3-b.bak
			dtc -W no-unit_address_vs_reg -I dts -O dtb -o $DTBFILE /boot/tmp.dts 
		fi
	fi
	rm /boot/tmp.dts
fi

DTBFILE=/boot/bcm2710-rpi-3-b-plus.dtb
if [ -f "$DTBFILE" ];then
	dtc -W no-unit_address_vs_reg -I dtb -O dts -o /boot/tmp.dts $DTBFILE
	if grep -q "brcm,pins = <0x8 0x7>;" /boot/tmp.dts; then
		if grep -q "brcm,function = <0x1>;" /boot/tmp.dts; then
      			echo "\n3B+";
			sed /boot/tmp.dts -i -e "s/brcm,function = <0x6>;/brcm,function = <0x1>;/"
			cp /boot/bcm2710-rpi-3-b-plus.dtb /boot/bcm2710-rpi-3-b-plus.bak
			dtc -W no-unit_address_vs_reg -I dts -O dtb -o $DTBFILE /boot/tmp.dts 
		fi
	fi
	rm /boot/tmp.dts
fi

DTBFILE=/bootbcm2710-rpi-cm3.dtb
if [ -f "$DTBFILE" ];then
	dtc -W no-unit_address_vs_reg -I dtb -O dts -o /boot/tmp.dts $DTBFILE
	if grep -q "brcm,pins = <0x8 0x7>;" /boot/tmp.dts; then
		if grep -q "brcm,function = <0x1>;" /boot/tmp.dts; then
      			echo "\nCM3";
			sed /boot/tmp.dts -i -e "s/brcm,function = <0x6>;/brcm,function = <0x1>;/"
			cp /boot/bcm2710-rpi-cm3.dtb /boot/bcm2710-rpi-cm3.bak
			dtc -W no-unit_address_vs_reg -I dts -O dtb -o $DTBFILE /boot/tmp.dts 
		fi
	fi
	rm /boot/tmp.dts
fi

cp /boot/config.txt /boot/tmp.txt

sed  -i "/dtparam=spi=/d" /boot/tmp.txt
sed  -i "/dtoverlay=ads7846/d" /boot/tmp.txt
sed  -i "/display_rotate=/d" /boot/tmp.txt
sed  -i "/dtoverlay=mzdpi/d" /boot/tmp.txt
sed  -i "/framebuffer_width=/d" /boot/tmp.txt
sed  -i "/framebuffer_height=/d" /boot/tmp.txt
sed  -i "/enable_dpi_lcd=/d" /boot/tmp.txt
sed  -i "/display_default_lcd=/d" /boot/tmp.txt
sed  -i "/dpi_group=/d" /boot/tmp.txt
sed  -i "/dpi_mode=/d" /boot/tmp.txt
sed  -i "/dpi_output_format=/d" /boot/tmp.txt
sed  -i "/hdmi_timings=/d" /boot/tmp.txt

cp /boot/tmp.txt /boot/config.txt
rm /boot/tmp.txt
