#!/bin/sh
cp /boot/config.txt /boot/tmp.txt

sed -i 's/display_auto/#display_auto/g' /boot/tmp.txt
sed -i 's/camera_auto/#camera_auto/g' /boot/tmp.txt
sed -i 's/dtoverlay/#dtoverlay/g' /boot/tmp.txt
sed -i 's/include/#include/g' /boot/tmp.txt

echo "include mzp354wv1b.txt" >> /boot/tmp.txt

cp /boot/tmp.txt /boot/config.txt

rm /boot/tmp.txt
