#!/bin/sh

do_dts_dtb() {
# now create dts file
cat <<\EOF > /boot/overlays/mzdpi6.dts && 
/dts-v1/;

/ {
	compatible = "brcm,bcm2708";

	fragment@0 {
		target = <0xdeadbeef>;

		__overlay__ {
			pinctrl-names = "default";
			pinctrl-0 = <0x1>;
		};
	};

	fragment@1 {
		target = <0xdeadbeef>;

		__overlay__ {

			dpi18_pins {
				brcm,pins = <0x0 0x1 0x2 0x3 0x4 0x5 0x6 0x7 0x8  0x09 0xc 0xd 0xe 0xf 0x10 0x11 0x14 0x15 0x16 0x17 0x18 0x19>;
				brcm,function = <0x6>;
				brcm,pull = <0x1>;
				linux,phandle = <0x1>;
				phandle = <0x1>;
			};
		};
	};

	__symbols__ {
		dpi18_pins = "/fragment@1/__overlay__/dpi18_pins";
	};

	__fixups__ {
		leds = "/fragment@0:target:0";
		gpio = "/fragment@1:target:0";
	};

	__local_fixups__ {
		fixup = "/fragment@0/__overlay__:pinctrl-0:0";
	};
};
EOF
dtc -I dts -O dtb -o /boot/overlays/mzdpi6.dtbo /boot/overlays/mzdpi6.dts
}

do_dts_dtb

cp /boot/config.txt /boot/tmp.txt

sed  -i "/dtparam=spi=/d" /boot/tmp.txt
sed  -i "/dtoverlay=ads7846/d" /boot/tmp.txt
sed  -i "/display_rotate=/d" /boot/tmp.txt
sed  -i "/dtoverlay=mzdpi/d" /boot/tmp.txt
sed  -i "/framebuffer_width=/d" /boot/tmp.txt
sed  -i "/framebuffer_height=/d" /boot/tmp.txt
sed  -i "/enable_dpi_lcd=/d" /boot/tmp.txt
sed  -i "/display_default_lcd=/d" /boot/tmp.txt
sed  -i "/dpi_group=/d" /boot/tmp.txt
sed  -i "/dpi_mode=/d" /boot/tmp.txt
sed  -i "/dpi_output_format=/d" /boot/tmp.txt
sed  -i "/hdmi_timings=/d" /boot/tmp.txt

echo "display_rotate=3" >> /boot/tmp.txt
echo "dtoverlay=mzdpi6" >> /boot/tmp.txt
echo "gpio=18=op,dh,pd" >> /boot/tmp.txt
echo "gpio=19=op,dh,pd" >> /boot/tmp.txt
echo "framebuffer_width=800" >> /boot/tmp.txt
echo "framebuffer_height=480" >> /boot/tmp.txt
echo "enable_dpi_lcd=1" >> /boot/tmp.txt
echo "display_default_lcd=1" >> /boot/tmp.txt
echo "dpi_group=2" >> /boot/tmp.txt
echo "dpi_mode=87" >> /boot/tmp.txt
echo "dpi_output_format=0x07f006" >> /boot/tmp.txt
echo "hdmi_timings=480 0 41 20 60 800 0 5 10 10 0 0 0 60 0 32000000 3" >> /boot/tmp.txt

cp /boot/tmp.txt /boot/config.txt

